/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ZoneRouteImport } from './routes/zone'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ZoneRoute = ZoneRouteImport.update({
  id: '/zone',
  path: '/zone',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/alerts': typeof AlertsRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/gallery': typeof GalleryRoute
  '/settings': typeof SettingsRoute
  '/zone': typeof ZoneRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/alerts': typeof AlertsRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/gallery': typeof GalleryRoute
  '/settings': typeof SettingsRoute
  '/zone': typeof ZoneRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/alerts': typeof AlertsRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/gallery': typeof GalleryRoute
  '/settings': typeof SettingsRoute
  '/zone': typeof ZoneRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/alerts'
    | '/customers'
    | '/dashboard'
    | '/gallery'
    | '/settings'
    | '/zone'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/alerts'
    | '/customers'
    | '/dashboard'
    | '/gallery'
    | '/settings'
    | '/zone'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/alerts'
    | '/customers'
    | '/dashboard'
    | '/gallery'
    | '/settings'
    | '/zone'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AlertsRoute: typeof AlertsRoute
  CustomersRoute: typeof CustomersRoute
  DashboardRoute: typeof DashboardRoute
  GalleryRoute: typeof GalleryRoute
  SettingsRoute: typeof SettingsRoute
  ZoneRoute: typeof ZoneRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zone': {
      id: '/zone'
      path: '/zone'
      fullPath: '/zone'
      preLoaderRoute: typeof ZoneRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AlertsRoute: AlertsRoute,
  CustomersRoute: CustomersRoute,
  DashboardRoute: DashboardRoute,
  GalleryRoute: GalleryRoute,
  SettingsRoute: SettingsRoute,
  ZoneRoute: ZoneRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
